(module $getter_setter_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (param i32)))
  (type (;3;) (func (param i32) (result i32)))
  (type (;4;) (func (param i32) (result f64)))
  (type (;5;) (func (param i32 i32)))
  (type (;6;) (func (param i32 i32) (result i32)))
  (type (;7;) (func (param i32 i32 i32)))
  (type (;8;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;9;) (func (param i32 f64)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_dd24417ed36fc46e" (func (;0;) (type 5)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;1;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 128 externref)
  (memory (;0;) 17)
  (export "__wbindgen_start" (func 1))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "memory" (memory 0))
  (export "foo_x_static" (func $foo_x_static))
  (export "foo_set_x_static" (func $foo_set_x_static))
  (export "__wbg_get_foo_x" (func $__wbg_get_foo_x))
  (export "foo_weird" (func $foo_weird))
  (export "__wbg_get_foo_y" (func $__wbg_get_foo_y))
  (export "foo_lone_getter" (func $foo_lone_getter))
  (export "foo_z" (func $foo_z))
  (export "__wbg_foo_free" (func $__wbg_foo_free))
  (export "__wbg_set_foo_x" (func $__wbg_set_foo_x))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "foo_set_weird" (func $foo_set_weird))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "__wbg_set_foo_y" (func $__wbg_set_foo_y))
  (export "foo_set_lone_setter" (func $foo_set_lone_setter))
  (export "foo_set_z" (func $foo_set_z))
  (func $foo_x_static (;2;) (type 1) (result i32))
  (func $foo_set_x_static (;3;) (type 2) (param i32))
  (func $__wbg_get_foo_x (;4;) (type 3) (param i32) (result i32))
  (func $foo_weird (;5;) (type 3) (param i32) (result i32))
  (func $__wbg_get_foo_y (;6;) (type 4) (param i32) (result f64))
  (func $foo_lone_getter (;7;) (type 4) (param i32) (result f64))
  (func $foo_z (;8;) (type 4) (param i32) (result f64))
  (func $__wbg_foo_free (;9;) (type 5) (param i32 i32))
  (func $__wbg_set_foo_x (;10;) (type 5) (param i32 i32))
  (func $__wbindgen_malloc (;11;) (type 6) (param i32 i32) (result i32))
  (func $foo_set_weird (;12;) (type 7) (param i32 i32 i32))
  (func $__wbindgen_realloc (;13;) (type 8) (param i32 i32 i32 i32) (result i32))
  (func $__wbg_set_foo_y (;14;) (type 9) (param i32 f64))
  (func $foo_set_lone_setter (;15;) (type 9) (param i32 f64))
  (func $foo_set_z (;16;) (type 9) (param i32 f64))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
