(module $js_namespace_export_reftest.wasm
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (type (;2;) (func (param i32)))
  (type (;3;) (func (param i32) (result i32)))
  (type (;4;) (func (param i32) (result f64)))
  (type (;5;) (func (param i32 i32)))
  (type (;6;) (func (param i32 i32) (result i32)))
  (type (;7;) (func (param i32 i32) (result i32 i32)))
  (type (;8;) (func (param i32 i32 i32)))
  (type (;9;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;10;) (func (param i32 i32 i32 i32) (result i32 i32)))
  (type (;11;) (func (param i32 f64)))
  (type (;12;) (func (param f64 f64) (result f64)))
  (import "./reference_test_bg.js" "__wbg___wbindgen_throw_dd24417ed36fc46e" (func (;0;) (type 5)))
  (import "./reference_test_bg.js" "__wbindgen_init_externref_table" (func (;1;) (type 0)))
  (table $__wbindgen_externrefs (;0;) 128 externref)
  (memory (;0;) 17)
  (export "__wbindgen_start" (func 1))
  (export "__wbindgen_externrefs" (table $__wbindgen_externrefs))
  (export "memory" (memory 0))
  (export "regular_function" (func $regular_function))
  (export "counter_increment" (func $counter_increment))
  (export "counter_new" (func $counter_new))
  (export "counter_value" (func $counter_value))
  (export "__wbg_get_point3d_x" (func $__wbg_get_point3d_x))
  (export "__wbg_get_point3d_y" (func $__wbg_get_point3d_y))
  (export "__wbg_get_point3d_z" (func $__wbg_get_point3d_z))
  (export "__wbg_get_point_x" (func $__wbg_get_point_x))
  (export "__wbg_get_point_y" (func $__wbg_get_point_y))
  (export "__wbg_get_rectangle_height" (func $__wbg_get_rectangle_height))
  (export "__wbg_get_rectangle_width" (func $__wbg_get_rectangle_width))
  (export "__wbg_counter_free" (func $__wbg_counter_free))
  (export "__wbg_point3d_free" (func $__wbg_point3d_free))
  (export "__wbg_point_free" (func $__wbg_point_free))
  (export "__wbg_rectangle_free" (func $__wbg_rectangle_free))
  (export "counter_set_value" (func $counter_set_value))
  (export "__wbindgen_malloc" (func $__wbindgen_malloc))
  (export "math_add" (func $math_add))
  (export "math_multiply" (func $math_multiply))
  (export "default_uppercase_uppercase" (func $"default_uppercase_uppercase multivalue shim"))
  (export "utils_string_uppercase" (func $"utils_string_uppercase multivalue shim"))
  (export "__wbindgen_free" (func $__wbindgen_free))
  (export "__wbindgen_realloc" (func $__wbindgen_realloc))
  (export "default_concat" (func $"default_concat multivalue shim"))
  (export "__wbg_set_point3d_x" (func $__wbg_set_point3d_x))
  (export "__wbg_set_point3d_y" (func $__wbg_set_point3d_y))
  (export "__wbg_set_point3d_z" (func $__wbg_set_point3d_z))
  (export "__wbg_set_point_x" (func $__wbg_set_point_x))
  (export "__wbg_set_point_y" (func $__wbg_set_point_y))
  (export "__wbg_set_rectangle_height" (func $__wbg_set_rectangle_height))
  (export "__wbg_set_rectangle_width" (func $__wbg_set_rectangle_width))
  (export "math_divide" (func $math_divide))
  (func $regular_function (;2;) (type 1) (result i32))
  (func $counter_increment (;3;) (type 2) (param i32))
  (func $counter_new (;4;) (type 3) (param i32) (result i32))
  (func $counter_value (;5;) (type 3) (param i32) (result i32))
  (func $__wbg_get_point3d_x (;6;) (type 4) (param i32) (result f64))
  (func $__wbg_get_point3d_y (;7;) (type 4) (param i32) (result f64))
  (func $__wbg_get_point3d_z (;8;) (type 4) (param i32) (result f64))
  (func $__wbg_get_point_x (;9;) (type 4) (param i32) (result f64))
  (func $__wbg_get_point_y (;10;) (type 4) (param i32) (result f64))
  (func $__wbg_get_rectangle_height (;11;) (type 4) (param i32) (result f64))
  (func $__wbg_get_rectangle_width (;12;) (type 4) (param i32) (result f64))
  (func $__wbg_counter_free (;13;) (type 5) (param i32 i32))
  (func $__wbg_point3d_free (;14;) (type 5) (param i32 i32))
  (func $__wbg_point_free (;15;) (type 5) (param i32 i32))
  (func $__wbg_rectangle_free (;16;) (type 5) (param i32 i32))
  (func $counter_set_value (;17;) (type 5) (param i32 i32))
  (func $__wbindgen_malloc (;18;) (type 6) (param i32 i32) (result i32))
  (func $math_add (;19;) (type 6) (param i32 i32) (result i32))
  (func $math_multiply (;20;) (type 6) (param i32 i32) (result i32))
  (func $"default_uppercase_uppercase multivalue shim" (;21;) (type 7) (param i32 i32) (result i32 i32))
  (func $"utils_string_uppercase multivalue shim" (;22;) (type 7) (param i32 i32) (result i32 i32))
  (func $__wbindgen_free (;23;) (type 8) (param i32 i32 i32))
  (func $__wbindgen_realloc (;24;) (type 9) (param i32 i32 i32 i32) (result i32))
  (func $"default_concat multivalue shim" (;25;) (type 10) (param i32 i32 i32 i32) (result i32 i32))
  (func $__wbg_set_point3d_x (;26;) (type 11) (param i32 f64))
  (func $__wbg_set_point3d_y (;27;) (type 11) (param i32 f64))
  (func $__wbg_set_point3d_z (;28;) (type 11) (param i32 f64))
  (func $__wbg_set_point_x (;29;) (type 11) (param i32 f64))
  (func $__wbg_set_point_y (;30;) (type 11) (param i32 f64))
  (func $__wbg_set_rectangle_height (;31;) (type 11) (param i32 f64))
  (func $__wbg_set_rectangle_width (;32;) (type 11) (param i32 f64))
  (func $math_divide (;33;) (type 12) (param f64 f64) (result f64))
  (@custom "target_features" (after code) "\08+\0bbulk-memory+\0fbulk-memory-opt+\16call-indirect-overlong+\0amultivalue+\0fmutable-globals+\13nontrapping-fptoint+\0freference-types+\08sign-ext")
)
